#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Angle(int distance)
{
	return distance * 360.0 / (2 * 3.14 * 26); //wheel ������ 26mm �
}

task main()
{
	float dist_angle;
	dist_angle = Angle(100.0);
	resetMotorEncoder(motorB);

	while (getMotorEncoder(motorB) < dist_angle)
	{
		setMotorSpeed(motorB, 10);
		setMotorSpeed(motorC, 10);
	}

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
}
