#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int turn90ByDegrees(float diameter, float length) //diameter = 53, length = 120
{
	return (((2 * 3.14 * length)/4) / (3.14 * diameter)) * 360.0;
}

task main()
{
	float dist_angle;
	dist_angle = turn90ByDegrees(53.0, 120.0);
	displayBigTextLine(5, "%f",dist_angle);
	sleep(2000);

	resetMotorEncoder(motorC);

	while (getMotorEncoder(motorC) < dist_angle)
	{
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 10);
	}

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
}
