#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float turnAnyDegrees(float diameter, float length, float any_degree)
{
	return ( ((2 * 3.14 * length) * (any_degree / 360) / (3.14 * diameter))) * 360.0;
}

task main()
{
	float dist_angle;
	dist_angle = turnAnyDegrees(52.0, 120.0, 180.0);
	displayBigTextLine(5, "%f",dist_angle);
	sleep(2000);

	resetMotorEncoder(motorC);

	while (getMotorEncoder(motorC) < dist_angle/2)
	{
		setMotorSpeed(motorB, -10);
		setMotorSpeed(motorC, 10);
	}

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
}
