#pragma config(Sensor, S2,     t_right,        sensorEV3_Touch)
#pragma config(Sensor, S3,     t_left,         sensorEV3_Touch)
#pragma config(Sensor, S4,     sonic,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          m_neck,        tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          m_right,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          m_left,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void AtoSwingNeck(int nCnt)
{
	for(int i=0; i<nCnt; i++)
	{
		setMotorSpeed(m_left, 10);
		setMotorSpeed(m_right, 10);
		sleep(200);
		setMotorSpeed(m_left, 0);
		setMotorSpeed(m_right, 0);

		setMotorSpeed(m_left, -10);
		setMotorSpeed(m_right, -10);
		sleep(200);
		setMotorSpeed(m_left, 0);
		setMotorSpeed(m_right, 0);

	}
}

task main()
{
	playSoundFile("Wall-e wow");
	sleep(2000);
	playSoundFile("Wall-e whistle");
	sleep(2000);

	AtoSwingNeck(3);

	playSoundFile("Wall-e Music");
	sleep(2000);
}
