#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S2,     t_right,        sensorEV3_Touch)
#pragma config(Sensor, S3,     t_left,         sensorEV3_Touch)
#pragma config(Sensor, S4,     sonic,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          m_neck,        tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          m_right,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          m_left,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void atoPlaySoundWithLock(int nSound)
{
	playSound(nSound);
	while(bSoundActive){}
}

task main()
{
	setSoundVolume(10);
	atoPlaySoundWithLock(soundBeepBeep);
	while(true)
	{
		int nDist = (int)(getUSDistance(sonic)*10);
		displayCenteredBigTextLine(5, "%d mm", nDist);
		displayCenteredBigTextLine(8, "%.1f cm", nDist/10);
		sleep(30);
	}

}
