#pragma config(Sensor, S1,     color,          sensorEV3_Color)
#pragma config(Sensor, S2,     t_right,        sensorEV3_Touch)
#pragma config(Sensor, S3,     t_left,         sensorEV3_Touch)
#pragma config(Sensor, S4,     sonic,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          m_neck,        tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          m_right,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          m_left,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnRight()
{
	setMotorSpeed(m_right, 0);
	setMotorSpeed(m_left, 50);
	sleep(200);
	setMotorSpeed(m_right, 0);
	setMotorSpeed(m_left, 0);
}

void turnLeft()
{
	setMotorSpeed(m_right, 50);
	setMotorSpeed(m_left, 0);
	sleep(200);
	setMotorSpeed(m_right, 0);
	setMotorSpeed(m_left, 0);
}

task main()
{
	while(true)
	{
		int nColor = getColorName(color);
		switch(nColor)
		{
			case colorBlack:
				turnRight();
				break;
			case colorWhite:
				turnLeft();
				break;
			default:
			turnRight();
		}
	}
}
