#pragma config(Sensor, S1,     color,          sensorEV3_Color)
#pragma config(Sensor, S2,     t_right,        sensorEV3_Touch)
#pragma config(Sensor, S3,     t_left,         sensorEV3_Touch)
#pragma config(Sensor, S4,     sonic,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          m_neck,        tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          m_right,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          m_left,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int calcBound()
{
	int bound;
	int black = 0;
	int white = 0;

	for(int i = 0; i<5; i++)
	{
		black += getColorReflected(color);
		sleep(10);
	}

	setMotorSpeed(m_left, 0);
	setMotorSpeed(m_right, 40);
	sleep(1000);
	setMotorSpeed(m_left, 0);
	setMotorSpeed(m_right, 0);

	for(int i=0; i<5; i++)
	{
		white += getColorReflected(color);
		sleep(1000);
	}

	bound = (white/5 + black/5) / 2;
	return bound;
}

task main()
{
	int gray = calcBound();
	displayBigTextLine(1, "%d", gray);
	sleep(5000);
}
